# Generated by Django 4.2 on 2023-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Tank', 'Танки'), ('Healer', 'Хилы'), ('DD', 'ДД'), ('Merchant', 'Торговцы'), ('Guildmaster', 'Гилдмастеры'), ('QuestGiver', 'Квестгиверы'), ('Blacksmith', 'Кузнецы'), ('Skinner', 'Кожевники'), ('PotionMaster', 'Зельевары'), ('SpellMaster', 'Мастер заклинаний')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
